In [1]:
import numpy as np

my_list = [1,2,3]
type(my_list)
np.array(my_list)

myarr = np.array(my_list)

In [1]:
import numpy as np

my_list = [[1,2,3],[2,3,4],[3,4,5]]

np.array(my_list)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [6]:
import numpy as np
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
import numpy as np
# np.zeros(2)

np.zeros((3,2)) # the first parameter is the number of rows, the second one is the quantity.

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [1]:
import numpy as np
# np.zeros(2)

np.ones((4,4)) # the first parameter is the shape, the second one is the quantity.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [2]:
np.linspace(0,10,11) # this is like np.arrange() but the last parameter is the quantity of the numbers in between the (0,10)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [3]:
len(np.linspace(0,10,11) )

11

In [4]:
np.eye(5)  # Identity matrix - its a part of linear algebra - it is same a square matrix, same numbers on rows, columns and  1 along the diagnoal.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Random distribution of DATA:

In [13]:
np.random.rand(2,2)

array([[0.39211654, 0.60161113],
       [0.81204271, 0.45686654]])

In [23]:
np.random.randn(4,3)

array([[ 1.488622  ,  1.34634349, -3.5629432 ],
       [-1.91628293, -0.17114679, -0.92379326],
       [-0.46390003, -0.53045327,  1.51065684],
       [ 1.11900077,  0.77063612,  1.04688912]])

In [30]:
np.random.randint(1,30,2) # the third will return the quantity of numbers. and it can return an array like this: (1,10,(2,3))

array([29,  7])

In [34]:
np.random.seed(42) # it sets a particular set of random numbers. and will return the same numbers in array.
np.random.rand(4) # and no matter how many times we run this, we get the same random numbers.

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [76]:
arr = np.arange(0,25)
arr.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
random_arrange = np.random.randint(0,10,7)
random_arrange


array([3, 7, 7, 2, 5, 4, 1])

In [53]:
random_arrange.max()


7

In [56]:
random_arrange.argmax()
# this means that the argument which is the max number, is sitting in the 1 position.

1

In [77]:
random_arrange = np.random.randint(0,10,8)
random_arrange.reshape(4,2)


array([[0, 9],
       [5, 8],
       [0, 9],
       [2, 6]])

In [60]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [62]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [63]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [150]:
import random
arr = np.arange(0,11)
y = arr[0:5]

for x in y :
    x = np.random.randint(0,4)
    y += x
print(list(arr)) # or we can simply type "arr" to see the results.

[5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 10]


In [81]:
arr = np.arange(0,11)
arr > 4


array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [159]:
boolean_amir = arr > 4
arr[boolean_amir]       # or we can use `arr[arr>4]` :
# arr[arr>4]

array([ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9, 10])

In [227]:
arr = np.arange(0,12)
arr + 4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [228]:
arr = np.arange(0,12)
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [229]:
arr = np.arange(0,12)
np.sqrt(arr) # رادیکال گرفتن از آرایه ما

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [230]:
arr = np.arange(0,12)
arr.sum()

66

In [232]:
arr.mean() # takes the average 

5.5

In [233]:
arr.var() # 

11.916666666666666

In [234]:
arr.std() # std = standard deviation 

3.452052529534663

In [238]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [237]:
arr_2d = np.arange(0,25).reshape(5,5)
arr_2d.shape

(5, 5)

اگر بخواییم فقط اولین جملات هر آرایه رو باهم در یک لیست ۲ در ۲ جمع کنیم باید به روش زیر جهت ۰ رو انتخاب کنیم. 
در لیست ۲ بعدی بالا اولین جملات هر لیست : ۰،۵،۱۰،۱۵،۲۰ هستند که وقتی جمع بشن باهم میشن ۵۰. 
در نتیجه در جواب پایین ما ۵۰ رو مشاهده میکنیم. 
همینطور برای سایر ستون ها.

In [239]:
arr_2d.sum(axis = 0 ) # این یعنی در ردیف اول این کار رو بکن = مجموع جملات در ردیف  ها 

array([50, 55, 60, 65, 70])

In [240]:
arr_2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])